# FROM gliderlabs/alpine:edge
FROM docker.io/alpine
MAINTAINER tangfeixiong <tangfx128@gmail.com>
ADD repositories /etc/apk/
RUN apk update \
  && apk add --no-cache bash ca-certificates curl libc6-compat netcat-openbsd \
  && rm -rf /var/cache/apk/* \
  && echo "<html><head><title>welcome</title></head><body><h1>hello world</h1></body></html>" >> /tmp/site/index.html
VOLUME /tmp/site
EXPOSE 80
CMD while true; do nc -l 80 < /tmp/site/index.html; done
